#################################################################
# Example render.yaml                                           #
# Do not use this file directly! Consult it for reference only. #
#################################################################
# List all services *except* PostgreSQL databases here
services:
  # A web service on the Ruby native runtime
  - type: web
    runtime: node
    name: phonebook-app
    numInstances: 3   # Manual scaling configuration. Default: 1
    region: cameroon # Default: oregon
    plan: free    # Default: starter
    branch: main      # Default: master
    buildCommand: npm install
   # preDeployCommand: bundle exec ruby migrate.rb
    startCommand: npm start
    autoDeploy: false # Disable automatic deploys
    #maxShutdownDelaySeconds: 120 # Increase graceful shutdown period. Default: 30, Max: 300
    domains: # Custom domains
      - example.com
      - www.example.org
    envVars: # Environment variables
      - key: API_BASE_URL
        value: https://api.example.com # Hardcoded value
      - key: APP_SECRET
        generateValue: true # Generate a base64-encoded 256-bit value
      - key: STRIPE_API_KEY
        sync: false # Prompt for a value in the Render Dashboard

